SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;

-- Bảng con trước
DELETE FROM DistributionLog;
ALTER TABLE DistributionLog AUTO_INCREMENT = 1;

DELETE FROM CampaignItem;
ALTER TABLE CampaignItem AUTO_INCREMENT = 1;

DELETE FROM SyncLogItem;
ALTER TABLE SyncLogItem AUTO_INCREMENT = 1;

DELETE FROM DonationItem;
ALTER TABLE DonationItem AUTO_INCREMENT = 1;

DELETE FROM WarehouseStock;
ALTER TABLE WarehouseStock AUTO_INCREMENT = 1;

DELETE FROM Campaign;
ALTER TABLE Campaign AUTO_INCREMENT = 1;

DELETE FROM SyncLog;
ALTER TABLE SyncLog AUTO_INCREMENT = 1;

DELETE FROM `User`;
ALTER TABLE `User` AUTO_INCREMENT = 1;

DELETE FROM Donation;
ALTER TABLE Donation AUTO_INCREMENT = 1;

DELETE FROM WarehouseItem;
ALTER TABLE WarehouseItem AUTO_INCREMENT = 1;

DELETE FROM DisasterLevel;
ALTER TABLE DisasterLevel AUTO_INCREMENT = 1;

DELETE FROM Warehouse;
ALTER TABLE Warehouse AUTO_INCREMENT = 1;

DELETE FROM Donor;
ALTER TABLE Donor AUTO_INCREMENT = 1;

DELETE FROM ItemCategory;
ALTER TABLE ItemCategory AUTO_INCREMENT = 1;

DELETE FROM DisasterType;
ALTER TABLE DisasterType AUTO_INCREMENT = 1;

DELETE FROM Area;
ALTER TABLE Area AUTO_INCREMENT = 1;

DELETE FROM Role;
ALTER TABLE Role AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;