-- Xem dữ liệu từ từng bảng
SELECT * FROM Area;
SELECT * FROM Campaign;
SELECT * FROM CampaignItem;
SELECT * FROM DisasterLevel;
SELECT * FROM DisasterType;
SELECT * FROM DistributionLog;
SELECT * FROM Donation;
SELECT * FROM DonationItem;
SELECT * FROM Donor;
SELECT * FROM ItemCategory;
SELECT * FROM Notification;
SELECT * FROM Role;
SELECT * FROM SyncLog;
SELECT * FROM SyncLogItem;
SELECT * FROM User;
SELECT * FROM Warehouse;
SELECT * FROM WarehouseItem;
SELECT * FROM WarehouseStock;